### ISSUE TITLE
제가 알기로는 mkdir로 디렉토리를 만든면 755로 폴더가 생성되요.

### ISSUE THREAD

**Issue by khw7096** [kybin/tor#19]
https://github.com/kybin/tor/blob/4c36eb742af4c11d6eb8d7a5a1afdd3efef05b3f/config.go#L31

혹시모를 보안 이슈가 발생할 수 있으니 755를 추천해요.
+112번째 줄도 하나 더 있어요.

**Comment by kybin** [comment]
한웅씨가 말하는 mkdir은 파이썬을 이야기 하는건가요?
Go의 os.Mkdir에는 파일 권한을 직접 입력하게 되어있더라구요.

보안에 문제가 있다는 말에는 일리가 있으니 수정은 하겠습니다.

**Comment by kybin** [comment]
Done: a4cf59e6dccc70a541d1a4ef3007f42efb266e26

**Comment by khw7096** [comment]
제가 말하는 mkdir은 리눅스 맥의 명령어였어요.
