### ISSUE TITLE
갯수를 구하는 함수인데 s값을 사용하지 않고 함수내부에서 remain 변수를 선언하는 이유가 궁금해요.

### ISSUE THREAD

**Issue by khw7096** [kybin/tor#21]
https://github.com/kybin/tor/blob/4c36eb742af4c11d6eb8d7a5a1afdd3efef05b3f/stringutil.go#L10

**Comment by kybin** [comment]
제가 그 아래 for문처럼 기존 스트링을 잘라가면서 어떤 문자열을 찾을 때
tor 내 다른 코드 (cursor.go) 에서 remain을 많이 썼거든요.
일관성 때문에 이렇게 했어요.

처음에 s로 받은건 string이라는 의미로 했구요.

**Comment by kybin** [comment]
일단은 닫을게요. 그래도 의문이 들면 다시 열어주세요.
